name: "CI/CD Pipelines"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checking out
      uses: actions/checkout@v3
      with:
        # Disabling shallow clone to ensure proper commit history is available for analysis
        fetch-depth: 0

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}