name: "CI/CD Pipelines"
on:
  push:
    branches-ignore:
      - l10n_develop
      - gh-pages
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'monitoring/grafana-dashboard.json'
      - 'screenshots/**'
    tags-ignore:
      - '*'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - 'data/static/i18n/*.json'
      - 'frontend/src/assets/i18n/*.json'
  
  workflow_dispatch:

env:
  NODE_DEFAULT_VERSION: 20
  ANGULAR_CLI_VERSION: 17
  CYCLONEDX_NPM_VERSION: '^1.12.0'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify Java version
      run: java -version
      

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=nadiroumaima_juice-shop
          -Dsonar.organization=nadiroumaima
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -X
  
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Adjust this based on your project requirements

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm ci

    # Step 4: Run tests
    - name: Run Cypress tests
      uses: cypress-io/github-action@v4
      with:
        browser: chrome # Options: chrome, firefox
        start: npm start # Start your application
        wait-on: http://localhost:3000 # Wait for your app to be available
        wait-on-timeout: 120 # Wait timeout in seconds

    # Step 5: Build the project
    - name: Build project
      run: npm run build

    # Step 6: Cache node_modules for faster builds (optional)
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-