name: "CI/CD piplines"
on:
  push: 
    branches: 
      - master
  workflow_dispatch:
jobs:
  setup:
    name: Setup
    runs-on : ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3
      - name: "Use Node.js 18"
        uses: actions/setup-node@5
      - name: Install Dependencies
        run: npm install

  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          output: results.sarif
          format: sarif
          # Adjust severity of non-security issues
          gh-code-scanning-compat: true
          # Force 0 exit code to allow SARIF file generation
          # This will hand over control about PR rejection to the GitHub side
          max-allowed-issues: 2147483647
      
      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: results.sarif
