name: "CI/CD Pipelines"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: npm install
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}    

  sonarqube:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Verify Java version
      run: java -version
      

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=nadiroumaima_juice-shop
          -Dsonar.organization=nadiroumaima
          -Dsonar.sources=.
          -Dsonar.host.url=https://sonarcloud.io
          -X
  
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install dependencies"
        run: npm install
        
      - name: Update TypeScript and Lodash types
        run: |
          npm install typescript@latest --save-dev
          npm install @types/lodash@latest --save-dev


      - name: "Build Angular frontend"
        run: npm run build:frontend

      - name: "Build backend with TypeScript"
        run: npm run build:server

      - name: "Save build artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/
            frontend/dist/