name: "CI/CD Pipelines"
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3

      - name: "Use Node.js 18"
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Install Dependencies"
        run: npm install

  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    needs: setup 
    services:
      sonarqube:
        image: sonarqube
        options: >-
          --health-cmd="curl -f http://localhost:9000/api/system/health" 
          --health-interval=10s 
          --health-retries=3
          -p 9000:9000
    steps:
      - name: "Check out Git repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "SonarQube Scan"
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
